#!/bin/bash
source="${BASH_SOURCE[0]}"
while [ -h "$source" ]; do
  dir="$(cd -P "$(dirname "$source")" && pwd)"
  source="$(readlink "$source")"
  [[ $source != /* ]] && source="$dir/$source"
done
dir="$(cd -P "$(dirname "$source")" && pwd)"

/Applications/Emacs.app/Contents/MacOS/Emacs -l $dir/contest.el
